{{protocol}}://{{host}}/AgentWrongExercises/GetWrongExercises?ssotoken={{ssotoken}}&agentid=123&chapterId=123&state=0&pageIndex=1&pageSize=10
###
{{protocol}}://{{host}}/AgentWrongExercises/GetWrongExercises?ssotoken={{ssotoken}}&agentId=1374390148525&chapterId=1374390105323&wrongExerciseType=0&state=2&pageIndex=1&pageSize=10


###
{{protocol}}://{{host}}/AgentWrongExercises/SaveFinalOperation?ssotoken={{ssotoken}}&schoolId=1374390147519&userId=1374390145432&gradeId=0&versionId=0&volumeId=1&subjectId=10&chapterId=124

###
{{protocol}}://{{host}}/AgentWrongExercises/GetFinalOperation?ssotoken={{ssotoken}}&schoolId=1374390147518&userId=1374390145432


###
{{protocol}}://{{host}}/AgentWrongExercises/GetUrgentChapters?ssotoken={{ssotoken}}&wrongexerciseTypeId=0&agentId=1374390148525&eBookId=1374390105601


###
http://localhost:10025/PersonalizedManual/Class/GetEChapter?ssotoken={{ssotoken}}