
@user="admin"

@password="hex@jenkins1"

###研发环境d
curl -u {{user}}:{{password}} http://192.168.0.218:28080/job/feature_ExerciseDomainServer_publish/build?token=gbtoken
###研发环境w
curl -u {{user}}:{{password}} http://192.168.0.218:28080/job/feature_ExerciseWebApiServer_publish/build?token=gbtoken




###测试环境w
curl -u {{user}}:{{password}} http://192.168.0.218:28080/job/zw4_ExerciseWebApiServer_publish/build?token=gbtoken

###
curl -u {{user}}:{{password}} http://192.168.0.218:28080/job/zw4_ExerciseDomainServer_publish/build?token=gbtoken

###
curl -u {{user}}:{{password}} http://192.168.0.218:28080/job/master_ExerciseWebApiServer_publish/build?token=gbtoken

###
curl -u {{user}}:{{password}} http://192.168.0.218:28080/job/master_ExerciseDomainServer_publish/build?token=gbtoken