###
Post http://localhost:7000/wxpay/login
Content-Type: application/json

{
    "Code": "0f1D0R0w3JtLu03xiu0w3ujxAU2D0R04"
}


###
Post http://localhost:7000/wxpay/GetUserPhone
Content-Type: application/json

{
  "Code": "0d1jkr0w3KZLA03NdB3w3zaGXV0jkr0u",
"EncryptedData": "HBbaFmk/gqpOuL6E/yuUYDrlGsSqKgup/Wi1Y86oreS/opBCLO0rzSejZhqeZ0McEA/vtFh4iGwHFAGzyVL0zYdVzfoqwQwlIYqrecY7SbvkIHbGzVoYc5AV6kV8kaHXOd0WRxYGgftaWU0ogvN0SZyOW4idaPu8gGunTl6II8hlM78gGToGENgwS1gJRqNJaq55idBQXIjKOTPtr2WZzA==",
"Iv": "IEg1Ek6TQdWiDJrr/6fiKQ=="
}


###
Post https://ai.myi.cn/wxpay/login
Content-Type: application/json

{
    "Code": "0d1QH1100YP9RP17cN000NZrFn2QH11F"
}


###
Post https://ai.myi.cn/wxpay/HandleWxPayNotify
Content-Type: application/json



###
https://ai.myi.cn/wxpay/GenOrder?openid=oQEQS5g1ftCKrExLwllhMfkcOwC0



