###
Post http://localhost:7000/wxpay/login
Content-Type: application/json

{
    "Code": "0a17xPGa1DXJiF0DWGFa17kJQ607xPGN"
}


###
Post http://localhost:7000/wxpay/GetUserPhone
Content-Type: application/json

{
  "Code": "0d1jkr0w3KZLA03NdB3w3zaGXV0jkr0u",
"EncryptedData": "HBbaFmk/gqpOuL6E/yuUYDrlGsSqKgup/Wi1Y86oreS/opBCLO0rzSejZhqeZ0McEA/vtFh4iGwHFAGzyVL0zYdVzfoqwQwlIYqrecY7SbvkIHbGzVoYc5AV6kV8kaHXOd0WRxYGgftaWU0ogvN0SZyOW4idaPu8gGunTl6II8hlM78gGToGENgwS1gJRqNJaq55idBQXIjKOTPtr2WZzA==",
"Iv": "IEg1Ek6TQdWiDJrr/6fiKQ=="
}


###
Post https://ai.myi.cn/api/wxpay/login
Content-Type: application/json

{
    "Code": "0f1xrM0w3WfeB039SJ0w39mtol2xrM0x"
}


###
Post https://ai.myi.cn/wxpay/HandleWxPayNotify
Content-Type: application/json



###
https://ai.myi.cn/api/wxpay/GenOrder?openid=oQEQS5pOpKg9oWIhmMcuX6VBMLHY
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJvUUVRUzVwT3BLZzlvV0lobU1jdVg2VkJNTEhZIiwibmJmIjoxNjgzNzg0NDU2LCJleHAiOjE2ODM4NzA4NTYsImlhdCI6MTY4Mzc4NDQ1NiwiaXNzIjoiaW5maW5pdGVsZWFybmluZyIsImF1ZCI6ImdwdCJ9.tCpnVv3gihKo3PB5f36_m1TwJx6mUYbsUOavMoilmT8

###
https://ai.myi.cn/api/wxpay/GenOrder?openid=oQEQS5pOpKg9oWIhmMcuX6VBMLHY
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJvUUVRUzVwT3BLZzlvV0lobU1jdVg2VkJNTEhZIiwibmJmIjoxNjgzNzg0NDU2LCJleHAiOjE2ODM4NzA4NTYsImlhdCI6MTY4Mzc4NDQ1NiwiaXNzIjoiaW5maW5pdGVsZWFybmluZyIsImF1ZCI6ImdwdCJ9.tCpnVv3gihKo3PB5f36_m1TwJx6mUYbsUOavMoilmT8

###
http://localhost:7000/wxpay/GenOrder?openid=oQEQS5pOpKg9oWIhmMcuX6VBMLHY
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJvUUVRUzVnMWZ0Q0tyRXhMd2xsaE1ma2NPd0MwIiwibmJmIjoxNjg0Mzk5NDM2LCJleHAiOjE2ODQ0ODU4MzYsImlhdCI6MTY4NDM5OTQzNiwiaXNzIjoiaW5maW5pdGVsZWFybmluZyIsImF1ZCI6ImdwdCJ9.dqlXhKwtgCWLg8eNL4McXUtJc375G68wJB62kNDcA3U

